# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170603_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
